"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteFromTodoList = exports.deleteTodo = exports.createTodo = exports.addTodo = exports.fetchSampleList = exports.updateSampleList = void 0;
var action_1 = require("./action");
exports.updateSampleList = action_1.createAction("app/sample/updateList");
exports.fetchSampleList = action_1.createAction("app/sample/fetchList");
exports.addTodo = action_1.createAction("app/todos/addTodo");
exports.createTodo = action_1.createAction("app/todos/createTodo");
exports.deleteTodo = action_1.createAction("app/todos/deleteTodo");
exports.deleteFromTodoList = action_1.createAction("app/todos/deleteFromTodoList");
